enable OpenMP flag if compiler supports fix MSVC error C3016: index variable in OpenMP 'for' statement must have signed integral type, since VS2013 only support OpenMP 2.5